apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    role: example-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      securityContext:
        runAsUser: 20000
        capabilities:
          drop:
          - ALL
      command: ["sleep", "3600"]