apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    role: example-pod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 20000
        capabilities:
          drop:
          - ALL
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 1
      command: ["sleep", "3600"]