apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
  labels:
    role: example-pod
spec:
  serviceAccountName: vault-service-account
  containers:
    - name: ubuntu
      image: ubuntu
      env:
      # - name: VAULT_ADDR
      #   value: "http://192.168.65.2:8200"
      - name: VAULT_ROLE
        value: internal-app
      command: ["sleep", "infinity"]
      securityContext:
        runAsUser: 0
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
      volumeMounts:
        - name: shared-data
          mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}






