apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
  labels:
    role: example-pod
spec:
  automountServiceAccountToken: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: vault-service-account
  containers:
    - name: ubuntu
      #checkov:skip=CKV_K8S_43:No image digest
      #checkov:skip=CKV_K8S_14:No image tag
      image: ubuntu
      env:
      # - name: VAULT_ADDR
      #   value: "http://192.168.65.2:8200"
      - name: VAULT_ROLE
        value: internal-app
      command: ["sleep", "infinity"]
      securityContext:
        readOnlyRootFilesystem: true
        runAsUser: 20000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
      volumeMounts:
        - name: shared-data
          mountPath: /data
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 1
  volumes:
    - name: shared-data
      emptyDir: {}






