apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-curl-pod
  labels:
    role: example-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          drop:
          - ALL
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
      volumeMounts:
        - name: shared-data
          mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}





