apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-curl-pod
  labels:
    role: example-pod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "infinity"]
      securityContext:
        readOnlyRootFilesystem: true
        runAsUser: 20000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
      volumeMounts:
        - name: shared-data
          mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}





