version: '2.1'
orbs:
  continuation: circleci/continuation@0.1
workflows:
  use-my-orb:
    jobs:
      - continuation/continue:
          configuration_path: ./continuation_config_file.yml



          