version: 2.1

jobs:
  continuation-of-previous-config:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "continuation"


workflows:
  continuation-workflow:
    jobs:
      - continuation-of-previous-config

            