version: 2.1



jobs:
  test_cont:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "continuation 1 executed"

workflows:
  cont1_workflow:
    jobs:
      - test_cont