name: Workflow 1

# Pipeline runs after a push on branch main
# only if at least one file
# inside src/server_1 or src/server_2 folders
# has been modified
permissions: read-all

on: 
  push:
    branches:
      - main
    paths:
      - 'src/server_1/**'
      - 'src/server_2/**'



jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Action test




        