# This is a basic workflow to help you get started with Actions

# name: CI

# Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "test" ]
#   pull_request:
#     branches: [ "test" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions: read-all

name: CI
on: 
  push:
    branches:
      - idk


jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Action test

  test2:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: node:14.16
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Action test

        

      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
